name: JdkTest
on:
  push:
    branches: [4.0-dev]
jobs:
  t:
    runs-on: codeberg-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle
      - name: Version
        run: java -version
