name: Probe1
run-name: Probe1 ${{ github.ref_name }}
on:
  push:
    branches: [4.0-dev]
permissions:
  contents: write
jobs:
  build:
    runs-on: codeberg-small
    env:
      HAS_KEYSTORE: ${{ secrets.KEYSTORE != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle
      - name: Echo
        run: echo "probe1 ok"
