name: Probe10
on:
  push:
    branches: [4.0-dev]
jobs:
  build:
    runs-on: codeberg-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Decode Keystore
        if: env.HAS_KEYSTORE == 'true'
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: test.txt
          fileDir: .
          encodedString: aGVsbG8=
      - name: Test upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: probe10-artifact
          path: gradlew
