name: UsesTest
on:
  push:
    branches: [4.0-dev]
jobs:
  t:
    runs-on: codeberg-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: ls | head -3
