name: Build, Deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: Decode Keystore
        id: decode_keystore
        if: ${{ secrets.KEYSTORE != '' && (github.event_name != 'pull_request' || github.ref_type == 'tag') }}
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ${{ vars.RELEASE_KEYSTORE }}
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Generate keystore.properties
        if: ${{ secrets.RELEASEKEYPASSWORD != '' && (github.event_name != 'pull_request' || github.ref_type == 'tag') }}
        run: |
          echo keystore.file="${{ vars.RELEASE_KEYSTORE }}" >> keystore.properties
          echo keystore.password="${{ secrets.RELEASESTOREPASSWORD }}" >> keystore.properties
          echo keystore.key.alias="${{ vars.RELEASE_KEY_ALIAS }}" >> keystore.properties
          echo keystore.key.password="${{ secrets.RELEASEKEYPASSWORD }}" >> keystore.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/4.0-dev' }}

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Build Release
        if: ${{ secrets.KEYSTORE != '' }}
        run: ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        if: ${{ secrets.KEYSTORE != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload Mapping
        if: ${{ secrets.KEYSTORE != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: ./app/build/outputs/mapping/release
